<a href="https://colab.research.google.com/github/pakpahansalma/python_for_datascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Numpy Create Array

In [ ]:
#@title 0-D Array

var_array = np.array(42)

print(var_array)

42


In [ ]:
#@title 1-D Array

var_array = np.array([1, 2, 3, 4, 5]) #1 dimensi

print(var_array)

[1 2 3 4 5]


In [ ]:
var_array = np.ones(5)
print(var_array)

[1. 1. 1. 1. 1.]


In [ ]:
var_array = np.zeros(4)
print(var_array)

[0. 0. 0. 0.]


In [ ]:
#setiap kali dijalankan ulang, nilainya berubah-ubah
var_array = np.random.random(6)
print(var_array)

[0.2517622  0.06860088 0.86215751 0.65284615 0.71573341 0.48271725]


In [ ]:
#@title 2-D Array

var_array = np.array([[1, 2, 3], [4, 5, 6]])
#var_array = np.array ([[],[]])
print(var_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#@title 3-D Array

var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(var_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#@title Check dimensi array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#@title Create array range
#numpy.arange(start, stop, step)

var_array = np.arange(1, 20, 2)
print(var_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# create with reshape
#var_array = np.arange(0:10)
var_array = np.arange(10).reshape((2, 5))
print(var_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create numpy text


var_array = np.array(['apple', 'banana', 'cherry'])
print(var_array)

['apple' 'banana' 'cherry']


## Numpy Array Indexing

In [ ]:
#@title Akses indeks

# 1-D
var_array = np.array([85, 55, 40, 90])

# mengakses data pada array
print(var_array[3])

90


In [ ]:
# 2-D
var_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# 0 = [1,2,3,4,5]
# 1 = [6,7,8,9,10]

#print(var_array[baris, kolom]
print(var_array[1, 2])

8


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# print(var_array[1, 1, 2])
print(var_array[1:2, :2, 2]

12


In [ ]:
#@title Operation indeks

var_array = np.array([1, 2, 3, 4])

print(var_array[2] + var_array[3])

7


In [ ]:
print(var_array[0] + var_array[2])

4


In [ ]:
#@title Slicing array

# 1-D
var_array = np.array([1, 2, 3, 4, 5, 6, 7])

print(var_array[3:])

[4 5 6 7]


In [ ]:
# 2-D
var_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var_array[0, 1:4])

[2 3 4]


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 0:2])

[10 11]


In [ ]:
#@title Iterating Arrays

var_array = np.array([1, 2, 3])

for x in var_array: #PERULANGAN
  print(x)

1
2
3


In [ ]:
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in var_array #melooping berdasarkan jlh matriksnya
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Numpy Array Join

In [ ]:
#@title Concatenate

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
var_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
var_array2 = np.array([[[4, 7, 9], [1, 6, 2]], [[3, 5, 8], [19, 10, 14]]])

arr = np.concatenate((var_array1, var_array2))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  7  9]
  [ 1  6  2]]

 [[ 3  5  8]
  [19 10 14]]]


In [ ]:
#@title Stack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2))
# arr = np.hstack((arr1, arr2))
# arr = np.vstack((arr1, arr2))
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Numpy Splitting

In [ ]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
newarr = np.array_split(arr, 2)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[1, 2, 3],
        [4, 5, 6]]])]


## Numpy Matriks

In [ ]:
matriks = [[1,2,3],
           [4,5,6],
           [7,8,9]]

matrik_np = np.array(matriks)
print(matrik_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#@title Operasi matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])


hasil = matrik_a + matrik_b
print("Hasil Penjumlahan:")
print(hasil)

Hasil Penjumlahan:
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [ ]:
hasil = matrik_a - matrik_b
print("Hasil Pengurangan:")
print(hasil)

Hasil Pengurangan:
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
# pangkat dengan power()

result_power = np.power(matrik_a, 2)
print("Hasil Perhitungan Pangkat (matrik_a pangkat 2):")
print(result_power)

Hasil Perhitungan Pangkat (matrik_a pangkat 2):
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# trigonometri dengan sin()

result_power = np.sin(matrik_a)
print("Hasil sin matrik_a:")
print(result_power)

Hasil sin matrik_a:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
#@title Transpose matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)


hasil = matrik_a.transpose()
print("\nMatrik kebalikan: ")
print(hasil)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrik kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#@title Reshape matrik

matrik_a = np.array([1, 2, 3, 4, 5, 6])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

# mengubah ukran ke 3x2
hasil = matrik_a.reshape(3, 2)

print("\nMengubah ke 3x2: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


In [ ]:
#@title Matrik flatten

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.flatten()

print("\nMatrik setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)

Matrik setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


## Numpy Statistik

In [ ]:
#@title rata-rata (mean)

data = np.array([12, 15, 18, 22, 30, 35, 40, 45, 55, 65])

mean = np.mean(data)
print("Rata-rata (mean):", mean)

Rata-rata (mean): 33.7


In [ ]:
#@title median

median = np.median(data)
print("Median:", median)

Median: 32.5


In [ ]:
#@title standard deviation

std_deviation = np.std(data)
print("Deviasi Standar (standard deviation):", std_deviation)

Deviasi Standar (standard deviation): 16.79315336677421


In [ ]:
#@title variansi (variance)

variance = np.var(data)
print("Variansi (variance):", variance)

Variansi (variance): 282.01


In [ ]:
#@title minimum dan maksimum

minimum = np.min(data)
maximum = np.max(data)
print("Nilai Minimum:", minimum)
print("Nilai Maksimum:", maximum)

Nilai Minimum: 12
Nilai Maksimum: 65


In [ ]:
#@title quartile

# Menghitung kuartil pertama (Q1) dan kuartil ketiga (Q3)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Kuartil Pertama (Q1):", q1)
print("Kuartil Ketiga (Q3):", q3)


# Menghitung rentang interkuartil (IQR)
iqr = q3 - q1
print("Rentang Interkuartil (IQR):", iqr)

Kuartil Pertama (Q1): 19.0
Kuartil Ketiga (Q3): 43.75
Rentang Interkuartil (IQR): 24.75


## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [ ]:
#pip install numpy

In [ ]:
import numpy as np

1D Array:

In [ ]:
array_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:")
print(array_1d)

1D Array:
[10 20 30 40 50]


2D Array:

In [ ]:
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D Array:")
print(array_2d)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


3D Array:

In [ ]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Numpy Join:

In [ ]:
#Stack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# arr = np.stack((arr1, arr2, arr3)) #Menggabungkan dengan sumbu baru
# arr = np.hstack((arr1, arr2, arr3)) # Menggabungkan secara horizontal (1D ke 1D)
# arr = np.vstack((arr1, arr2, arr3)) # Menggabungkan secara vertikal (2D)
arr = np.dstack((arr1, arr2, arr3)) # Menggabungkan secara kedalaman (3D)


print(arr)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


Numpy Split:

In [ ]:
#2D
arr = np.array([[3, 6], [2, 4], [1, 5], [8, 10], [7, 9], [11, 12]])
newarr = np.array_split(arr, 3) #membagi array menjadi 3 sub

print(newarr)

[array([[3, 6],
       [2, 4]]), array([[ 1,  5],
       [ 8, 10]]), array([[ 7,  9],
       [11, 12]])]


Operasi Matriks


In [ ]:
#Operasi matrik

matrik_x = np.array([
    [2, 1, 3],
    [6, 5, 2],
    [7, 12, 9]])

matrik_y = np.array([
    [2, 2, 3],
    [6, 5, 4],
    [10, 8, 7]])


hasil = matrik_x * matrik_y
print("Hasil Perkalian:")
print(hasil)

Hasil Perkalian:
[[ 4  2  9]
 [36 25  8]
 [70 96 63]]


## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

In [ ]:
# Membuat array 3x4 dengan rentang 10-30
array_3x4 = np.arange(10, 22).reshape(3, 4)  # Rentang 10 hingga 21 (22 tidak termasuk)
print("Array 3x4:")
print(array_3x4)

# Melakukan flatten
flattened_array = array_3x4.flatten()
print("\nFlattened Array:")
print(flattened_array)

# Menghitung nilai statistik
mean_value = np.mean(flattened_array)
median_value = np.median(flattened_array)
std_deviation = np.std(flattened_array)
min_value = np.min(flattened_array)
max_value = np.max(flattened_array)

print("\nNilai Statistik:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")
print(f"Min: {min_value}")
print(f"Max: {max_value}")

Array 3x4:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Flattened Array:
[10 11 12 13 14 15 16 17 18 19 20 21]

Nilai Statistik:
Mean: 15.5
Median: 15.5
Standard Deviation: 3.452052529534663
Min: 10
Max: 21


In [ ]:
# Membuat array 3x4 dengan rentang 10-30
array_4x5 = np.arange(10, 30).reshape(4, 5)  # Rentang 10 hingga 29 (30 tidak termasuk) = 20 elemen
print("Array 4x5:")
print(array_4x5)

# Melakukan flatten
flattened_array = array_4x5.flatten()
print("\nFlattened Array:")
print(flattened_array)

# Menghitung nilai statistik
mean_value = np.mean(flattened_array)
median_value = np.median(flattened_array)
std_deviation = np.std(flattened_array)
min_value = np.min(flattened_array)
max_value = np.max(flattened_array)

print("\nNilai Statistik:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")
print(f"Min: {min_value}")
print(f"Max: {max_value}")

Array 4x5:
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Flattened Array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

Nilai Statistik:
Mean: 19.5
Median: 19.5
Standard Deviation: 5.766281297335398
Min: 10
Max: 29


In [ ]:
#Numpy Array

# Membuat array 3x4 dengan rentang 10-30
array_3x4 = np.arange(10, 30).reshape(3, 4)
print("Array 3x4:")
print(array_3x4)

# Melakukan flatten
flattened_array = array_3x4.flatten()
print("\nFlattened Array:")
print(flattened_array)

# Menghitung nilai statistik
mean_value = np.mean(flattened_array)
median_value = np.median(flattened_array)
std_deviation = np.std(flattened_array)
min_value = np.min(flattened_array)
max_value = np.max(flattened_array)

print("\nNilai Statistik:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")
print(f"Min: {min_value}")
print(f"Max: {max_value}")

ValueError: cannot reshape array of size 20 into shape (3,4)